/**
Given a string A, find if there is any subsequence that repeats itself.
A subsequence of a string is defined as a sequence of characters generated by deleting some characters in the string without changing the order of the remaining characters.
NOTE : sub-sequence length should be greater than or equal to 2.
https://www.interviewbit.com/problems/repeating-subsequence/
*/

public class Solution {
    public int anytwo(String a) {
        
        int n = a.length()+1;
        int[][] cache = new int[n][n];
        for (int i = 1; i < n; i++) {
            for (int j = 1; j < n; j++) {
                if(a.charAt(i-1) == a.charAt(j-1) && i!=j) {
                    cache[i][j] = 1+cache[i-1][j-1];
                }else {
                    cache[i][j] = Math.max(cache[i-1][j],cache[i][j-1]);
                }
                if(cache[i][j] >=2) return 1;
            }
        }
        return 0;
    }
}
